version: "3"
services:  
  impaqtive-mysql:
    image: percona:5.6.41
    privileged: true
    restart: always
    container_name: impaqtivebarn-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Welcome@1
    volumes:
      - perconadata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - impaqtivevps  
networks:
  impaqtivevps:
volumes:
  perconadata: